### PR TITLE
Change all private class properties to protected

### PR DESCRIPTION
**Pull request by goodevilgenius**
There may be instances in which an individual might want to extend any of the classes in this library. Having private properties in classes may make it difficult to extend classes, without having to copy a lot of the original code to compensate for unavailable private methods.

This PR rectifies that by changing all private properties/methods to protected.

### CODE REVIEW

**Comment by cmfcmf** [comment]
Hi @goodevilgenius,
thank you for your contribution! May I ask you why you want to overwrite one of the classes? Can you give me an example of something you would like to do? I am hesitant of making everything protected, as I don't want the properties to be considered a public stable api.

**Comment by goodevilgenius** [comment]
@cmfcmf My other PR (#106) implements the change that I wanted to make by simply extending the `OpenWeatherMap` class. The addition of a zip code search would have been simple to do if I could've overwritten one of the private methods.

If you merge my other PR, I, personally, don't need to extend any of the classes, but others might have similar needs.

**Comment by cmfcmf** [comment]
Alright, I see. I would rather not merge this then. If the properties were protected, you had implemented the zip code feature privately and no one else would have profited. Having the properties private forced you to make a PR so that everyone could benefit - which is great. 👍

**Comment by goodevilgenius** [comment]
I would've still submitted a PR as well, but would've implemented in as an extending class, in case it took you a while to merge my PR.

But clearly you're on top of this.

**Pull request closed without merging**
