### PR TITLE
cnt modified

### PR DESCRIPTION
**Pull request by pablopereira27**
Changed to the maximum days allowed in OpenWeatherMap free version

### CODE REVIEW

**Comment by cmfcmf** [comment]
Hi @pablopereira27!

Could you please also adjust the docblocks of the methods to reflect the change? Thanks!

**Comment by pablopereira27** [comment]
docblocks adjusted

**Comment by cmfcmf** [comment]
Thanks!

**Comment by cmfcmf** [comment]
I just released version 2.0.4 including this fix.

**Pull request merged**
