### PR TITLE
Version 3 Update

### LINKED ISSUE #130: Dealing with Internal error: 500001
The library should handle OWM's "Internal error: 500001", currently it's not handled at all. When this response is received, it continues with creating a new CurrentWeather object. Temperature and other values become 0.

The response that comes back from OWM server:

`<?xml version="1.0" encoding="UTF-8"?>
<ClientError><cod>500</cod><message>Internal error: 500001</message></ClientError>`

[More about Internal error: 500001](https://openweathermap.desk.com/customer/portal/questions/17207111-periodic-internal-error-5-1-)

### PR DESCRIPTION
**Pull request by cmfcmf**
This PR accumulates some breaking changes for version 3, based on #72. I will release version 3 once this PR is merged.

- closes #130

### CODE REVIEW

**Comment by KarelWintersky** [comment]
Valid :)

**Comment by KarelWintersky** [comment]
a little fix:

Must be `°F`, not an alone `F`

**Comment by cmfcmf** [comment]
> a little fix:
> 
> Must be `°F`, not an alone `F`

Good point! Fixed in https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/pull/134/commits/6c5eee9035922d2b607256d3fddb6fcc5dbe02db

**Comment by cmfcmf** [comment]
I am considering to drop support for PHP 5.3, 5.4 and 5.5. Here's why:
- PHP <= 5.5 is EOL for almost 3 years
- Many libraries in the ecosystem require PHP 5.6. When I [played around with support](https://github.com/cmfcmf/OpenWeatherMap-PHP-Api/pull/134/commits/d2391152db221099fb3c3a9668a309b827df990f) for [PSR-6 Cache](https://www.php-fig.org/psr/psr-6/) (instead of the current custom cache implementation), I quickly ran into issues with `cache/array-adapter` because it requires at least PHP 5.6.
- I have only briefly looked into PSR-17 and PSR-18 (HTTP Client), but library support for PHP 5 looks similarly bad over there.

**If you are watching this repository, please feel free to comment on this and/or give a :+1: or :-1:!**

**Comment by KarelWintersky** [comment]
All my actual code required PHP 7+ 

You can drop support for PHP before 7 version :)

**Comment by cmfcmf** [comment]
I have now dropped support for PHP < 7 completely, since `psr/http-client` requires at least PHP 7.0. There are two things left for me to do before merging this PR and releasing 3.0.0:
- [ ] test the weather history data integration
- [ ] use new PHP features (types, short array syntax, ...)

**Pull request merged**
