### PR TITLE
Improve assertions and TestCase class

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Replace the `PHPUnit_Framework_TestCase` with `PHPUnit\Framework\TestCase` to support latest PHPUnit version.
- Using the `assertSame` to improve `assertEquals` assertions.

### CODE REVIEW

**Review by cmfcmf — CHANGES_REQUESTED** [review]
Thank you! It looks like you need to aditionally specify the return type on the `setUp` function as `: void` to make it compatible with the function in the superclass. Then this should be good to go 🚀

**Comment by peter279k** [comment]
> Thank you! It looks like you need to aditionally specify the return type on the `setUp` function as `: void` to make it compatible with the function in the superclass. Then this should be good to go

Just notice that the `setUp` method with `void` or `non-void` is for different PHPUnit versions.

**Comment by cmfcmf** [comment]
> Just notice that the `setUp` method with `void` or `non-void` is for different PHPUnit versions.

True! I'll see if I can make it work or if I have to drop testing on the old (and long deprecated) PHP 7.0.

**Comment by cmfcmf** [comment]
After removing PHP 7.0, this now works as expected. Thank you again!

**Pull request merged**
