### PR TITLE
Added interface JsonSerializable to Util\Unit class 

### PR DESCRIPTION
**Pull request by 1Franck**
this help to properly json_encode() the current weather result

### CODE REVIEW

**Comment by peter279k** [comment]
Coding style is failed, could you fix that, @1Franck :)?

**Comment by peter279k** [comment]
@1Franck, it still has coding style error, and you can check that [link](https://github.styleci.io/analyses/vQ0Ykr?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Comment by 1Franck** [comment]
should be good now :)

**Comment by 1Franck** [comment]
I've updated the branch now with the latest merge. It would be very helpful if you could merge and release a new version for this PR when you got time. Thanks :)

**Comment by 1Franck** [comment]
Thank you! :)

**Pull request merged**
