### PR TITLE
Fixed Sun Rise/Set bug on forecast

### PR DESCRIPTION
**Pull request by Braunson**
It was not setting sun rise/set properly and always defaulted to NOW for both rise and set.

### CODE REVIEW

**Comment by Braunson** [comment]
Holdup, seems to be setting the sun rise/set to the same thing when calling a forecast.. hmm thoughts?

**Comment by Braunson** [comment]
As OWM's API doesn't return the proper information in the forecast, this PR will only set the Sun Rise/Set for each day to the parent's day you are requesting which is not helpful if you rely on exact correct information for each day after the current requested day.

**Comment by cmfcmf** [comment]
> Update: seems like OWM's API isn't returning a sun rise/set within the $xml->forecast->time object.. I'm using a free API key right now, could that have anything to do with it? @cmfcmf 

I'm afraid I have no idea.

Anyways, thank you for your investigation @Braunson!

**Comment by Braunson** [comment]
@cmfcmf No problem. It's weird why OWM only returns Sun rise/set for the current day.. I ended up not using their sun rise/set and instead implemented this page.. (for any others with this issue)

https://packagist.org/packages/martindilling/sunny

**Pull request closed without merging**
