### PR TITLE
Updated the UVIndex implementation

### PR DESCRIPTION
**Pull request by roelvanhintum**

### CODE REVIEW

**Comment by cmfcmf** [comment]
Hi @roelvanhintum!
Thank you for your PR – would you be able to also take a look at the failing tests?

https://travis-ci.org/cmfcmf/OpenWeatherMap-PHP-Api/jobs/522113766#L499

**Comment by roelvanhintum** [comment]
@cmfcmf i've changed the tests, but travis-ci is still having some problems with composer i can't figure out.

**Comment by cmfcmf** [comment]
Thank you for adjusting the tests. The build was failing on hhvm, which Composer doesn't support any longer. I therefore removed support for hhvm.

I'm sorry this takes so long - I'm hesitant to merge this as this, because this would break backwards compatiblity with the current implementation, if I'm reading the changes correctly. I hope to find time next week to take another look at your PR and possibly make it backwards compatible (maybe via an opt-in switch).

**Comment by roelvanhintum** [comment]
I couldn't match the old implementation with the API, which was the reason i changed it.
https://openweathermap.org/api/uvi

Maybe this should be pushed to a major release, to make clear things can break?

**Comment by cmfcmf** [comment]
I've gone through this PR and updated some minor bits and pieces. I also fixed historic uv index retrieval and tests. This should be good to go now. 
I will release this, as you suggested, as part of a new major version: 3.0.0. Before that, I'll fix and improve some other bits and pieces in #134 based on #72.

Thank you again for your work and patience, @roelvanhintum!

**Comment by roelvanhintum** [comment]
@cmfcmf You're welcome and thank you!

**Pull request merged**
